# -*- coding: utf-8 -*-
"""table_chunking_comparison (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONKMIfEeoOAPZj2jMXKNF_M_THBCdPzi

# Teste D — Chunking de Tabelas: Formato Tabular vs. Texto Natural

Compara duas estratégias de chunking para tabelas extraídas com **Docling**,
usando os **mesmos modelos do pipeline v2** (Qwen3 + SPLADE) e FAISS local.

| Estratégia | Descrição |
|---|---|
| **Tabular** | 1 chunk por tabela em Markdown |
| **Texto Natural** | 1 chunk por linha: `col: val \| col: val` |

**PDF:** `Classico(2003) - Janaina Lais Pacheco Lara Morandin.pdf` · **Página 5**

---
## 0. Instalações e Imports
"""

!pip install docling sentence-transformers transformers torch faiss-cpu PyMuPDF -q
!sudo apt install tesseract-ocr tesseract-ocr-por tesseract-ocr-eng -y -qq

import os, json, gc, tempfile
from pathlib import Path
from itertools import groupby

import numpy as np
import pandas as pd
import torch
import faiss
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForMaskedLM
from IPython.display import display, Markdown

from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions, TesseractCliOcrOptions
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling_core.types.doc import TableItem

print('OK')

"""---
## 1. Google Drive e Configuração
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

# Usar str() com o acento correto — Docling recebe bytes via tempfile,
# entao o caminho só precisa ser válido para open() do Python.
PDF_PATH    = '/content/drive/MyDrive/Pdfextractor/data/PDFs não vetorizados/Classico(2003) - Janaina Lais Pacheco Lara Morandin.pdf'
TARGET_PAGE = 5
SOURCE_NAME = 'Classico(2003) - Janaina Lais Pacheco Lara Morandin'

print(f'PDF      : {PDF_PATH}')
print(f'Existe?  : {os.path.exists(PDF_PATH)}')
print(f'Pagina   : {TARGET_PAGE}')

"""---
## 2. Tesseract (idêntico ao pipeline v2)
"""

candidates = [
    '/usr/share/tesseract-ocr/5/tessdata',
    '/usr/share/tesseract-ocr/4.00/tessdata',
    '/usr/share/tesseract-ocr/tessdata',
    '/usr/share/tessdata',
]
tessdata = next((p for p in candidates if os.path.isdir(p)),
                '/usr/share/tesseract-ocr/5/tessdata')
os.environ['TESSDATA_PREFIX'] = tessdata
needed  = ['osd.traineddata', 'por.traineddata', 'eng.traineddata']
missing = [f for f in needed if not os.path.isfile(os.path.join(tessdata, f))]
if missing:
    os.system('apt-get install -y -qq tesseract-ocr-por tesseract-ocr-eng 2>&1')
print(f'Tesseract OK -> {tessdata}')

"""---
## 3. Modelos de Embedding (Qwen3 + SPLADE — pipeline v2)
"""

print('Carregando Qwen3-Embedding-0.6B...')
dense_model = SentenceTransformer('Qwen/Qwen3-Embedding-0.6B')

SPARSE_MODEL_NAME = 'opensearch-project/opensearch-neural-sparse-encoding-doc-v2-distill'
print('Carregando SPLADE...')
sparse_tokenizer = AutoTokenizer.from_pretrained(SPARSE_MODEL_NAME)
sparse_model     = AutoModelForMaskedLM.from_pretrained(SPARSE_MODEL_NAME)

print(f'Dim densa: {dense_model.get_sentence_embedding_dimension()}')


# Funções idênticas ao pipeline v2
def gerar_vetores_densos_batch(textos: list, batch_size: int = 8) -> list:
    embeddings = dense_model.encode(
        textos, batch_size=batch_size,
        normalize_embeddings=True, show_progress_bar=True
    )
    return [emb.tolist() for emb in embeddings]


def gerar_vetor_esparso(texto: str) -> dict:
    tokens = sparse_tokenizer(
        texto, return_tensors='pt',
        max_length=512, truncation=True, padding='max_length'
    )
    with torch.no_grad():
        output    = sparse_model(**tokens)
        ativacoes = torch.relu(output.logits)
        max_at, _ = ativacoes.max(dim=1)
        max_at    = max_at.squeeze(0)
        indices   = (max_at > 0).nonzero(as_tuple=True)[0].tolist()
        valores   = max_at[indices].tolist()
    if not indices:
        indices, valores = [0], [0.0]
    return {'indices': indices, 'values': valores}


print('Modelos OK.')

"""---
## 4. Conversão e Extração de Tabelas com Docling

Usa bytes + tempfile — **mesmo padrão do `converter_pdf_bytes()` do pipeline v2**.
Necessário porque o Docling não aceita caminhos com acentos/espaços diretamente.
"""

def converter_pdf_bytes_local(pdf_path: str):
    """
    Lê o PDF como bytes e converte via tempfile.
    Padrão idêntico ao converter_pdf_bytes() do pipeline v2.
    """
    # 1. Ler bytes
    with open(pdf_path, 'rb') as f:
        pdf_bytes = f.read()
    print(f'  PDF lido: {len(pdf_bytes)/1024:.1f} KB')

    # 2. Configuração idêntica ao pipeline v2
    opts = PdfPipelineOptions()
    opts.do_ocr             = True
    opts.do_table_structure = True
    opts.table_structure_options.do_cell_matching = True
    opts.ocr_options = TesseractCliOcrOptions(
        lang=['por', 'eng'], force_full_page_ocr=True
    )
    converter = DocumentConverter(
        format_options={InputFormat.PDF: PdfFormatOption(pipeline_options=opts)}
    )

    # 3. Gravar em tempfile e converter
    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp:
        tmp.write(pdf_bytes)
        tmp_path = tmp.name
    try:
        return converter.convert(tmp_path).document
    finally:
        try:
            os.remove(tmp_path)
        except OSError:
            pass


def extrair_tabelas_pagina(doc, target_page: int) -> list:
    """
    Percorre doc.iterate_items(), filtra TableItems da pagina alvo.
    Extrai grid via element.data.grid; fallback para parse de Markdown.
    """
    tabelas, t_counter = [], 0

    for element, _level in doc.iterate_items():
        if not isinstance(element, TableItem):
            continue

        page_no = None
        if hasattr(element, 'prov') and element.prov:
            page_no = element.prov[0].page_no
        if page_no != target_page:
            continue

        t_counter += 1

        try:
            grid = element.data.grid
            raw  = [[cell.text.strip() if cell.text else '' for cell in row]
                    for row in grid]
        except AttributeError:
            # Fallback: parsear Markdown exportado pelo Docling
            md    = element.export_to_markdown() if hasattr(element, 'export_to_markdown') else ''
            lines = [ln.strip() for ln in md.splitlines() if ln.strip().startswith('|')]
            raw   = [[c.strip() for c in ln.strip('|').split('|')] for ln in lines]
            raw   = [r for r in raw if not all(set(c) <= set('-: ') for c in r)]

        header = raw[0] if raw else []
        rows   = raw[1:] if len(raw) > 1 else []

        tabelas.append({
            'table_num': t_counter,
            'page_no':   page_no,
            'header':    header,
            'rows':      rows,
        })

    return tabelas


print('Convertendo com Docling (OCR completo) — pode demorar ~1-2 min...')
doc     = converter_pdf_bytes_local(PDF_PATH)
tabelas = extrair_tabelas_pagina(doc, TARGET_PAGE)

print(f'\nTabelas encontradas na pagina {TARGET_PAGE}: {len(tabelas)}')
for t in tabelas:
    print(f'  Tabela {t["table_num"]}: {len(t["rows"])} linhas x {len(t["header"])} colunas')

for t in tabelas:
    display(Markdown(f"### Tabela {t['table_num']} — pagina {t['page_no']}"))
    df = pd.DataFrame(t['rows'], columns=t['header'])
    display(df)
    print()

"""---
## 5. Estratégia A — Tabular (Markdown)

1 chunk por tabela. Compatível com `tipo: 'tabela'` do `montar_payload()` do pipeline v2.
"""

def tabela_para_markdown(t: dict) -> str:
    header, rows = t['header'], t['rows']
    if not header:
        return ''
    widths = [len(h) for h in header]
    for row in rows:
        for i, cell in enumerate(row):
            if i < len(widths):
                widths[i] = max(widths[i], len(cell))
    def fmt(cells):
        return '| ' + ' | '.join(str(cells[i]).ljust(widths[i] if i < len(widths) else 5)
                                  for i in range(len(cells))) + ' |'
    sep   = '| ' + ' | '.join('-' * w for w in widths) + ' |'
    lines = [fmt(header), sep]
    for row in rows:
        padded = row + [''] * (len(header) - len(row))
        lines.append(fmt(padded[:len(header)]))
    return '\n'.join(lines)


def gerar_chunks_tabulares(tabelas: list, source: str) -> list:
    chunks = []
    for t in tabelas:
        md = tabela_para_markdown(t)
        if not md:
            continue
        chunks.append({
            'chunk_id':  f'tabular_p{t["page_no"]}_t{t["table_num"]}',
            'strategy':  'tabular',
            'page':      t['page_no'],
            'table_num': t['table_num'],
            'source':    source,
            'n_rows':    len(t['rows']),
            'n_cols':    len(t['header']),
            'text':      md,
            'chars':     len(md),
            'tipo':      'tabela',
        })
    return chunks


tabular_chunks = gerar_chunks_tabulares(tabelas, SOURCE_NAME)
print(f'{len(tabular_chunks)} chunk(s) tabular(es)\n')
for c in tabular_chunks:
    display(Markdown(f"### `{c['chunk_id']}` — {c['n_rows']}L x {c['n_cols']}C | {c['chars']} chars"))
    display(Markdown(c['text']))
    print()

"""---
## 6. Estratégia B — Texto Natural (por linha)

Cada linha → `"Col1: val | Col2: val | ..."` com cabeçalho embutido.
Compatível com `tipo: 'texto'` do pipeline v2.
"""

def gerar_chunks_texto(tabelas: list, source: str) -> list:
    chunks = []
    for t in tabelas:
        header = t['header']
        for row_i, row in enumerate(t['rows']):
            pares = []
            for col_i, col_name in enumerate(header):
                val = row[col_i].strip() if col_i < len(row) else ''
                if val:
                    pares.append(f'{col_name}: {val}')
            if not pares:
                continue
            texto = ' | '.join(pares)
            chunks.append({
                'chunk_id':  f'text_p{t["page_no"]}_t{t["table_num"]}_r{row_i+1}',
                'strategy':  'text_natural',
                'page':      t['page_no'],
                'table_num': t['table_num'],
                'row_num':   row_i + 1,
                'source':    source,
                'text':      texto,
                'chars':     len(texto),
                'tipo':      'texto',
            })
    return chunks


text_chunks = gerar_chunks_texto(tabelas, SOURCE_NAME)
print(f'{len(text_chunks)} chunk(s) de texto natural\n')
for c in text_chunks:
    print(f"[{c['chunk_id']}] {c['chars']} chars")
    print(f"  {c['text']}")

"""---
## 7. Resumo Estatístico dos Chunks
"""

rows_stat = []
for c in tabular_chunks:
    rows_stat.append({'tabela': f"Tabela {c['table_num']}", 'estrategia': 'Tabular (Markdown)',
                      'n_chunks': 1, 'chars_total': c['chars'], 'chars_medio': c['chars'],
                      'chars_min': c['chars'], 'chars_max': c['chars']})
sorted_tc = sorted(text_chunks, key=lambda x: x['table_num'])
for tnum, grp in groupby(sorted_tc, key=lambda x: x['table_num']):
    grp   = list(grp)
    chars = [c['chars'] for c in grp]
    rows_stat.append({'tabela': f"Tabela {tnum}", 'estrategia': 'Texto Natural (por linha)',
                      'n_chunks': len(grp), 'chars_total': sum(chars),
                      'chars_medio': round(float(np.mean(chars)),1),
                      'chars_min': min(chars), 'chars_max': max(chars)})
display(Markdown('### Distribuição de Chunks por Estratégia'))
display(pd.DataFrame(rows_stat))

"""---
## 8. Embeddings — Qwen3 (denso) + SPLADE (esparso)
"""

all_chunks = tabular_chunks + text_chunks
all_texts  = [c['text'] for c in all_chunks]

print(f'Gerando vetores densos para {len(all_chunks)} chunks (Qwen3)...')
dense_vecs = gerar_vetores_densos_batch(all_texts, batch_size=8)
print('Vetores densos OK.')

print(f'Gerando vetores esparsos (SPLADE) para {len(all_chunks)} chunks...')
sparse_vecs = []
for i, txt in enumerate(all_texts):
    sv = gerar_vetor_esparso(txt)
    sparse_vecs.append(sv)
    if (i+1) % 5 == 0 or (i+1) == len(all_texts):
        print(f'  [{i+1}/{len(all_texts)}] tokens ativos: {len(sv["indices"])}')
for i, c in enumerate(all_chunks):
    c['dense_vec']  = dense_vecs[i]
    c['sparse_vec'] = sparse_vecs[i]
print('Vetores esparsos OK.')

"""---
## 9. Índices FAISS e Funções de Busca

Dense: Inner Product com vetores normalizados (= cosine, igual ao Qdrant Cloud).
Sparse: dot product manual sobre vocabulário ativo (replica Qdrant sparse).
"""

def build_dense_index(chunks: list) -> faiss.IndexFlatIP:
    vecs = np.array([c['dense_vec'] for c in chunks], dtype='float32')
    idx  = faiss.IndexFlatIP(vecs.shape[1])
    idx.add(vecs)
    return idx


def sparse_dot(q_sv: dict, c_sv: dict) -> float:
    q_map = dict(zip(q_sv['indices'], q_sv['values']))
    return sum(q_map.get(i, 0.0) * v for i, v in zip(c_sv['indices'], c_sv['values']))


def buscar_dense(query: str, faiss_idx, chunks: list, k: int = 3) -> list:
    q_emb = dense_model.encode([query], normalize_embeddings=True).astype('float32')
    scores, idxs = faiss_idx.search(q_emb, min(k, len(chunks)))
    return [{'rank': r+1, 'score': round(float(scores[0][r]),4),
             'chunk_id': chunks[idxs[0][r]]['chunk_id'],
             'text': chunks[idxs[0][r]]['text']}
            for r in range(len(idxs[0])) if idxs[0][r] < len(chunks)]


def buscar_sparse(query: str, chunks: list, k: int = 3) -> list:
    q_sv   = gerar_vetor_esparso(query)
    scored = sorted([(sparse_dot(q_sv, c['sparse_vec']), i)
                     for i, c in enumerate(chunks)], reverse=True)
    return [{'rank': r+1, 'score': round(scored[r][0],4),
             'chunk_id': chunks[scored[r][1]]['chunk_id'],
             'text': chunks[scored[r][1]]['text']}
            for r in range(min(k, len(scored)))]


idx_tab  = build_dense_index(tabular_chunks)
idx_text = build_dense_index(text_chunks)
print('Índices FAISS prontos.')

"""---
## 10. Queries de Teste

> ⚠️ **Adapte as queries abaixo ao conteúdo real das tabelas** após ver a seção 4.
"""

# EDITE AQUI com base no que você viu na seção 4 --------------------------------
QUERIES = [
    'Quantidade de frutos colhidos em 10 anos nas três árvores-mães, ainda que mutiladas?',
    'Pêso em quilogramas dos frutos colhidos em 10 anos nas três árvores-mães?'
]
# -----------------------------------------------------------------------------
print(f'{len(QUERIES)} queries definidas.')

"""---
## 11. Execução das Queries — Dense + Sparse por Estratégia
"""

results_log = []

for query in QUERIES:
    display(Markdown(f'---\n### Consulta: "{query}"'))

    # ── Dense
    display(Markdown('**Dense (Qwen3)**'))
    res_tab_d  = buscar_dense(query, idx_tab,  tabular_chunks, k=min(2, len(tabular_chunks)))
    res_txt_d  = buscar_dense(query, idx_text, text_chunks,    k=3)
    best_tab_d = res_tab_d[0]['score']  if res_tab_d else 0.0
    best_txt_d = res_txt_d[0]['score']  if res_txt_d else 0.0

    print('  [Tabular]')
    for r in res_tab_d:
        prev = r['text'][:100].replace('\n', ' ')
        print(f"    [{r['rank']}] {r['score']:.4f} | {r['chunk_id']}")
        print(f"         {prev}{'...' if len(r['text'])>100 else ''}")
    print('  [Texto Natural]')
    for r in res_txt_d:
        print(f"    [{r['rank']}] {r['score']:.4f} | {r['chunk_id']}")
        print(f"         {r['text'][:100]}{'...' if len(r['text'])>100 else ''}")

    winner_d = 'Tabular' if best_tab_d >= best_txt_d else 'Texto Natural'
    print(f'  >> Dense: {winner_d}  (delta={abs(best_tab_d-best_txt_d):.4f})')

    # ── Sparse
    display(Markdown('**Sparse (SPLADE)**'))
    res_tab_s  = buscar_sparse(query, tabular_chunks, k=min(2, len(tabular_chunks)))
    res_txt_s  = buscar_sparse(query, text_chunks,    k=3)
    best_tab_s = res_tab_s[0]['score'] if res_tab_s else 0.0
    best_txt_s = res_txt_s[0]['score'] if res_txt_s else 0.0

    print('  [Tabular]')
    for r in res_tab_s:
        print(f"    [{r['rank']}] {r['score']:.4f} | {r['chunk_id']}")
    print('  [Texto Natural]')
    for r in res_txt_s:
        print(f"    [{r['rank']}] {r['score']:.4f} | {r['chunk_id']}")

    winner_s = 'Tabular' if best_tab_s >= best_txt_s else 'Texto Natural'
    print(f'  >> Sparse: {winner_s}  (delta={abs(best_tab_s-best_txt_s):.4f})')

    results_log.append({
        'query': query,
        'dense_tab': round(best_tab_d,4), 'dense_text': round(best_txt_d,4),
        'sparse_tab': round(best_tab_s,4), 'sparse_text': round(best_txt_s,4),
        'winner_dense': winner_d, 'winner_sparse': winner_s,
        'delta_dense': round(abs(best_tab_d-best_txt_d),4),
        'delta_sparse': round(abs(best_tab_s-best_txt_s),4),
    })

"""---
## 12. Placar Final
"""

df_res = pd.DataFrame(results_log)
display(Markdown('### Resultado por Query'))
display(df_res[['query','dense_tab','dense_text','winner_dense',
                          'sparse_tab','sparse_text','winner_sparse']])

wins_tab_d = (df_res['winner_dense']  == 'Tabular').sum()
wins_txt_d = (df_res['winner_dense']  == 'Texto Natural').sum()
wins_tab_s = (df_res['winner_sparse'] == 'Tabular').sum()
wins_txt_s = (df_res['winner_sparse'] == 'Texto Natural').sum()
avg_tab_d  = df_res['dense_tab'].mean()
avg_txt_d  = df_res['dense_text'].mean()
avg_tab_s  = df_res['sparse_tab'].mean()
avg_txt_s  = df_res['sparse_text'].mean()

display(Markdown('### Placar Geral'))
print(f'  DENSE  -> Tabular: {wins_tab_d} v avg={avg_tab_d:.4f}  |  Texto Natural: {wins_txt_d} v avg={avg_txt_d:.4f}')
print(f'  SPARSE -> Tabular: {wins_tab_s} v avg={avg_tab_s:.4f}  |  Texto Natural: {wins_txt_s} v avg={avg_txt_s:.4f}')

ven_d = 'Tabular' if avg_tab_d >= avg_txt_d else 'Texto Natural'
ven_s = 'Tabular' if avg_tab_s >= avg_txt_s else 'Texto Natural'
display(Markdown(f'\n**Dense (Qwen3):** {ven_d}  |  **Sparse (SPLADE):** {ven_s}'))

"""---
## 13. Análise Qualitativa — Pipeline SB100

### Tabular (Markdown)
| Aspecto | Avaliação |
|---|---|
| Estrutura preservada | ✅ Cabeçalhos e relações entre colunas intactos |
| Compatibilidade pipeline v2 | ✅ Detectado como `tipo: 'tabela'` em `montar_payload()` |
| Qualidade embedding Qwen3 | ⚠️ Markdown estruturado dilui a semântica densa |
| Granularidade RAG | ❌ LLM recebe tabela inteira mesmo para query pontual |
| Melhor para | Tabelas pequenas (≤ 5 linhas), queries de visão geral |

### Texto Natural (por linha)
| Aspecto | Avaliação |
|---|---|
| Estrutura preservada | ⚠️ Relações entre linhas se perdem |
| Compatibilidade pipeline v2 | ✅ `tipo: 'texto'`, integração direta |
| Qualidade embedding Qwen3 | ✅ Prosa curta → melhor alinhamento semântico |
| Granularidade RAG | ✅ Recupera exatamente a linha relevante |
| Melhor para | Tabelas grandes (> 5 linhas), queries sobre valores específicos |

### Implementação Híbrida Recomendada para o Qdrant

Vetorizar com **Texto Natural** (melhor similarity) + Markdown completo no payload.

```python
# Adaptar montar_payload() para incluir campo extra:
payload = {
    'content':         chunk_texto_natural,  # <- embedding (denso + esparso)
    'tabela_markdown': tabela_md_completa,   # <- payload Qdrant para contexto LLM
    'tipo':            'tabela',
    # ... demais campos de montar_payload() ...
}
```
"""

output = {
    'metadata': {
        'fonte': SOURCE_NAME, 'pagina': TARGET_PAGE,
        'dense_model': 'Qwen/Qwen3-Embedding-0.6B',
        'sparse_model': SPARSE_MODEL_NAME,
    },
    'tabular_chunks': [{k: v for k, v in c.items() if k not in ('dense_vec','sparse_vec')}
                       for c in tabular_chunks],
    'text_natural_chunks': [{k: v for k, v in c.items() if k not in ('dense_vec','sparse_vec')}
                            for c in text_chunks],
    'comparacao': results_log,
}
OUT = '/content/drive/MyDrive/Pdfextractor/data/table_chunking_results.json'
with open(OUT, 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)
print(f'Exportado -> {OUT}')